Yoyu(proje10)/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Yoyu_proje10_.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

Yoyu(proje10)/Controllers/MusteriController.cs
using Dapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yoyu_proje10_.Models;

namespace Yoyu_proje10_.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        public ActionResult Index()
        {
            return View(DP.ReturnList<MusteriModel>("MusteriListele")); 
        }

        public ActionResult EY(int id = 0) //ekle yenile
        {
            if (id == 0)

                return View();
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@MusteriNo", id);
                return View(DP.ReturnList<MusteriModel>("MusteriSirala", param).FirstOrDefault<MusteriModel>());
            }

        }
        [HttpPost]
        public ActionResult EY(MusteriModel musteri)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@MusteriNo", musteri.MusteriNo);
            param.Add("@MusteriAdi", musteri.MusteriAdi);
            param.Add("@MusteriSoyadi", musteri.MusteriSoyadi);
            param.Add("@MusteriMail", musteri.MusteriMail);
            param.Add("@MusteriAdres", musteri.MusteriAdres);
            param.Add("@MusteriTelefon", musteri.MusteriTelefon);
            param.Add("@MusteriYas", musteri.MusteriYas);
            DP.EXReturn("MusteriEY", param);
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id = 0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("MusteriNo", id);
            DP.EXReturn("MusteriSil", param);
            return RedirectToAction("Index");
        }

    }
}

Yoyu(proje10)/Controllers/SergiController.cs
using Dapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yoyu_proje10_.Models;

namespace Yoyu_proje10_.Controllers
{
    public class SergiController : Controller
    {
        // GET: Sergi
        public ActionResult Index()
        {
            return View(DP.ReturnList<SergiModel>("SergiListele")); 
        }

    
        public ActionResult EY(int id = 0) //ekle yenile
        {
            if (id == 0)

                return View();
            else
            {
                DynamicParameters param = new DynamicParameters();
                param.Add("@SergiNo", id);
                return View(DP.ReturnList<SergiModel>("SergiSirala", param).FirstOrDefault<SergiModel>());
            }

        }
        [HttpPost]
        public ActionResult EY(SergiModel sergi)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("@SergiNo", sergi.SergiNo);
            param.Add("@SergiAdi", sergi.SergiAdi);
            param.Add("@SergiAcilisTarihi", sergi.SergiAcilisTarihi);
            param.Add("@SergiKapanisTarihi", sergi.SergiKapanisTarihi);
            param.Add("@SergiAdres", sergi.SergiAdres);
            param.Add("@SergiTelefon", sergi.SergiTelefon);
            param.Add("@SergiBiletFiyat", sergi.SergiBiletFiyat);
            DP.EXReturn("SergiEY", param);
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id = 0)
        {
            DynamicParameters param = new DynamicParameters();
            param.Add("SergiNo", id);
            DP.EXReturn("SergiSil", param);
            return RedirectToAction("Index");
        }
    }
}

Yoyu(proje10)/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Yoyu_proje10_.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
    }
}

Yoyu(proje10)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Yoyu(proje10)/Views/Shared/_LayoutPageAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/AdminTema/css/styles.css" rel="stylesheet" />
    <link href="~/AdminTema/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="@Url.Action("Index","Home")">Photo</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="@Url.Action("Login","Accounts")">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="@Url.Action("Index","Admin")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Yoyu
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>

                        <a class="nav-link" href="@Url.Action("Index","Sergi")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Sergiler
                        </a>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Sanatçılar ve Eserleri

                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="@Url.Action("Index","Sanatci")">Sanatçı</a>
                                <a class="nav-link" href="@Url.Action("Index","SanatEseri")">SanatEseri</a>
                            </nav>
                        </div>


                        @*<a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
            Müşteriler
            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
        </a>*@
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="@Url.Action("Index","Fotograf")">Fotoğraf</a>
                                        <a class="nav-link" href="@Url.Action("Index","Fotografci")">Fotoğrafçı</a>
                                    </nav>
                                </div>
                                @*<a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                    Error
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>*@
                                @*<div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="401.html">401 Page</a>
                        <a class="nav-link" href="404.html">404 Page</a>
                        <a class="nav-link" href="500.html">500 Page</a>
                    </nav>
                </div>*@
                            </nav>
                        </div>
                        @*<div class="sb-sidenav-menu-heading">Addons</div>
        <a class="nav-link" href="charts.html">
            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
            Charts
        </a>
        <a class="nav-link" href="tables.html">
            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
            Tables
        </a>*@
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Photo
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @*<h1 class="mt-4">Dashboard</h1>*@
                    <ol class="breadcrumb mb-4">
                        <li class="breadcrumb-item active"></li>
                    </ol>
                    @RenderBody()

                </div>


            </main>

            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/AdminTema/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/AdminTema/assets/demo/chart-area-demo.js"></script>
    <script src="~/AdminTema/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="~/AdminTema/js/datatables-simple-demo.js"></script>
</body>
</html>

Yoyu(proje10)/Views/Shared/_LayoutPageAnasayfa.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Free minimal portfolio web site template,minmal portfolio,porfolio,bootstrap template,html template,photography " />
    <title>Home - YOYU</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600,700,800,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/AnasayfaTema/assets/css/main.min.css">
    <link rel="stylesheet" href="~/AnasayfaTema/assets/css/rtl.css">

</head>

<body>
    <div class="nav-main">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <a href="index.html" class="logo">
                    <img src="~/UserTema/assets/images/Yoyu.png" style="width:120px" alt="">
                </a>
                @*<a class="navbar-brand font-weight-bold" href="index.html">art.studio</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="index.html">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="project.html">Project</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="about.html">About</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav ml-auto">

                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","User")">User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Admin")">Admin</a>
                        </li>

                    </ul>
                </div>
            </nav>
            <!--end:Nav -->
        </div>
    </div>
    <!--end:Navigation -->
    <main role="main">
        @RenderBody()
        <section class="intro">
            <div class="container">
                <div class="row d-flex  align-items-start">
                    <div class="col-md-11">
                        <h1 class="display-3">The Art of Imagination.<br>Award-winning Design &amp; Craft Studio.</h1>
                    </div>
                </div>
            </div>
        </section>
        <!--end:Intro -->
        <section class="space-md">
            <!-- portfolio -->
            <div id="portfolio" class="container">
                <div id="portfolio-filters">
                    <ul id="filters" class="p-0">
                        <li><a href="*" class="active">everything</a></li>
                        <li><a href=".digital">Digital</a></li>
                        <li><a href=".branding">Web Design</a></li>
                        <li><a href=".campaigns">Marketing</a></li>
                    </ul>
                </div>
                <div class="grid" data-cols="3" data-margin="0" data-height="1" data-masonry='{ "columnWidth": 200, "itemSelector": ".entry" }'>
                    <!-- entry -->
                    <div class="entry work-entry branding">
                        <a href="project.html">
                            <div class="entry-image imageBG" data-img="../AnasayfaTema/src/assets/img/photo-1558212628-ad7f5fb28c5e.jpg">
                                <img src="../AnasayfaTema/src/assets/img/photo-1558212628-ad7f5fb28c5e.jpg" />
                            </div>
                            ---------------------------------------------------------------------
                            <div class="work-entry-hover">
                                <div class="work-entry-content">
                                    <div class="work-entry-title">Liber Finance</div>
                                    <div class="work-entry-cat">Web</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- end:entry -->
                    <div class="entry work-entry digital">
                        <a href="project.html">
                            <div class="entry-image imageBG" data-img="../AnasayfaTema/assets/img/photo-1558180702-95f1c3ae2ca3.jpg"></div>
                            <div class="work-entry-hover">
                                <div class="work-entry-content">
                                    <div class="work-entry-title">Aramark</div>
                                    <div class="work-entry-cat">Marketing</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- end:entry -->
                    <div class="entry work-entry campaigns">
                        <a href="project.html">
                            <div class="entry-image imageBG" data-img="../AnasayfaTema/assets/img/photo-1558118720-fa5cdebe6b3a.jpg"></div>
                            <div class="work-entry-hover">
                                <div class="work-entry-content">
                                    <div class="work-entry-title">Portfolio page</div>
                                    <div class="work-entry-cat">web design</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- end:entry -->
                    <div class="entry work-entry branding">
                        <a href="project.html">
                            <div class="entry-image imageBG" data-img="../AnasayfaTema/assets/img/photo-1558100984-01e6cd6fc9aa.jpg"></div>
                            <div class="work-entry-hover">
                                <div class="work-entry-content">
                                    <div class="work-entry-title">Sunday Breakfast</div>
                                    <div class="work-entry-cat">Branding</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- end:entry -->
                    <div class="entry work-entry campaigns h2">
                        <a href="project.html">
                            <div class="entry-image imageBG" data-img="../AnasayfaTema/assets/img/photo-1494475673543-6a6a27143fc8.jpg"></div>
                            <div class="work-entry-hover">
                                <div class="work-entry-content">
                                    <div class="work-entry-title">Sunday Breakfast</div>
                                    <div class="work-entry-cat">All</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- end:entry -->
                    <div class="entry work-entry branding digital">
                        <a href="project.html">
                            <div class="entry-image imageBG" data-img="../AnasayfaTema/assets/img/photo-1557941760-987c3f403d5a.jpg"></div>
                            <div class="work-entry-hover">
                                <div class="work-entry-content">
                                    <div class="work-entry-title">Pine Street</div>
                                    <div class="work-entry-cat">Web + Digital</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- end:entry -->
                    <div class="entry work-entry digital">
                        <a href="project.html">
                            <div class="entry-image imageBG" data-img="../AnasayfaTema/assets/img/photo-1534073828943-f801091bb18c.jpg"></div>
                            <div class="work-entry-hover">
                                <div class="work-entry-content">
                                    <div class="work-entry-title">Mobipaid</div>
                                    <div class="work-entry-cat">Branding</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- end:entry -->
                    <div class="entry work-entry brading">
                        <a href="project.html">
                            <div class="entry-image imageBG" data-img="../AnasayfaTema/assets/img/photo-1484755560615-a4c64e778a6c.jpg"></div>
                            <div class="work-entry-hover">
                                <div class="work-entry-content">
                                    <div class="work-entry-title">Solo Solution</div>
                                    <div class="work-entry-cat">Logo</div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- end:entry -->


                </div>
            </div>
            <!-- /end:portfolio -->
        </section>
    </main>
    <footer class="position-relative">
        <div class="container">
            <div class="row">

                <div class="col-lg-auto mt-4">
                    <p class="mb-4">sharebootstrap.com</p>
                </div>
                <div class="col-lg-3 mt-4 ml-auto">
                    <p>
                        dayy GmbH
                        <br> sarajevska. 32
                        <br> 71000 sarajevo
                        <br> fbih
                    </p>
                    <a href="mailto:hi@yourdomain.com"><span style="text-decoration: underline;">hi@sharebootstrap.com</span></a>
                </div>
                <div class="col-lg-3 mt-4 ml-auto">
                    <ul class="list-unstyled footer-link">
                        <li><a href="#">instagram</a></li>
                        <li><a href="#">facebook</a></li>
                        <li><a href="#">twitter</a></li>
                    </ul>
                </div>
                <div class="col-lg-auto ml-lg-auto mt-4">
                    <ul class="list-unstyled footer-link">
                        <li><a href="#">instagram</a></li>
                        <li><a href="#">facebook</a></li>
                        <li><a href="#">twitter</a></li>
                        <!-- Please note.You are not allowed to remove credit link.Please respect that.-->
                        <li><a href="https://sharebootstrap.com">dev by sharebootstrap</a></li>
                    </ul>
                </div>
            </div>
            <!--/.row-->
        </div>
        <!--/.container-->
    </footer>
    <script src="~/AnasayfaTema/assets/js/main.min.js"></script>
</body>

</html>

Yoyu(proje10)/Views/Shared/_LayoutPageUser.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>YOYU</title>

    <!-- Bootstrap core CSS -->
    <link href="~/UserTema/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/UserTema/assets/css/fontawesome.css">

    <link rel="stylesheet" href="~/UserTema/assets/css/templatemo-cyborg-gaming.css">
    <link rel="stylesheet" href="~/UserTema/assets/css/owl.css">
    <link rel="stylesheet" href="~/UserTema/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />
    <!--

    TemplateMo 579 Cyborg Gaming

    https://templatemo.com/tm-579-cyborg-gaming

    -->
</head>

<body>

    <!-- ***** Preloader Start ***** -->
    <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo">
                            <img src="~/UserTema/assets/images/Yoyu.png" style="width:120px" alt="">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Search End ***** -->
                        @*<div class="search-input">
                            <form id="search" action="#">
                                <input type="text" placeholder="Type Something" id='searchText' name="searchKeyword" onkeypress="handle" />
                                <i class="fa fa-search"></i>
                            </form>
                        </div>*@
                        <!-- ***** Search End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            @*<li><a href="index.html" class="active">Home</a></li>*@
                            <li><a href="@Url.Action("Index","Musteri")">Müşteri</a></li>
                            <li><a href="@Url.Action("Index","Kiralama")">Kiralama</a></li>
                            <li><a href="@Url.Action("Index","Siparis")">Sipariş</a></li>
                            <li><a href="@Url.Action("Index","User")">User <img src="~/UserTema/assets/images/profile-header.jpg" alt=""></a></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>

    </header>
    <!-- ***** Header Area End ***** -->

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-content">
                    @RenderBody()
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
           
                    <br />

                    <!-- ***** Banner Start ***** -->
                    <!--<div class="main-banner">
        <div class="row">
            <div class="col-lg-7">
                <div class="header-text">
                    <h6>Welcome To Cyborg</h6>
                    <h4><em>Browse</em> Our Popular Games Here</h4>
                    <div class="main-button">
                        <a href="browse.html">Browse Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>-->
                    <!-- ***** Banner End ***** -->



                </div>
            </div>
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>
                        Copyright © 2036 <a href="#">Cyborg Gaming</a> Company. All rights reserved.

                        <br>Design: <a href="https://templatemo.com" target="_blank" title="free CSS templates">TemplateMo</a>  Distributed By <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>


    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/UserTema/vendor/jquery/jquery.min.js"></script>
    <script src="~/UserTema/vendor/bootstrap/js/bootstrap.min.js"></script>

    <script src="~/UserTema/assets/js/isotope.min.js"></script>
    <script src="~/UserTema/assets/js/owl-carousel.js"></script>
    <script src="~/UserTema/assets/js/tabs.js"></script>
    <script src="~/UserTema/assets/js/popup.js"></script>
    <script src="~/UserTema/assets/js/custom.js"></script>


</body>

</html>